import { DEFAULT_PI_MODEL, DEFAULT_PI_PROVIDER, DEFAULT_PI_THINKING_LEVEL, DEFAULT_STATE_DIR_NAME } from "./defaults.js";

export function usage(): string {
  return [
    "Usage:",
    "  decomp-orchestrator [global flags] init-run [--goal-kind kind] [--goal-value n] [--desired-workers n] [--candidate-limit n]",
    "  decomp-orchestrator [global flags] tick [--run-id id] [--candidate-limit n]",
    "  decomp-orchestrator [global flags] worker [--run-id id] [--worker-id id] [--report-type type] [--base-rev rev] [--ttl-seconds n]",
    "  decomp-orchestrator [global flags] trigger-agent [--run-id id] [--max-workers n] [--worker-thinking-level level] [--idle-sleep-ms n] [--max-iterations n] [--max-idle-iterations n] [replan flags]",
    "  decomp-orchestrator [global flags] bootstrap [same flags as trigger-agent]",
    "  decomp-orchestrator [global flags] babysit [--run-id id] [trigger flags] [--max-restarts n] [--restart-delay-ms n]",
    "  decomp-orchestrator [global flags] recover-leases [--run-id id] [--force] [--lease-id id] [--worker-id id] [--reason text]",
    "  decomp-orchestrator [global flags] regression-check [--run-id id] [--target changes_all] [--report-title title] [--report-max-rows n]",
    "  decomp-orchestrator [global flags] status",
    "",
    "Global flags:",
    "  --repo-root <path>          default: current working directory",
    `  --state-dir <path>         default: <repo-root>/${DEFAULT_STATE_DIR_NAME}`,
    "  --dry-run-agents           do not call Pi SDK; write prompts as outputs",
    `  --provider <name>          default: ${DEFAULT_PI_PROVIDER}`,
    `  --model <name>             default: ${DEFAULT_PI_MODEL}`,
    `  --thinking-level <level>   default: ${DEFAULT_PI_THINKING_LEVEL}`,
    "  --agent-timeout-seconds n  bound each live Pi session; default: no timeout",
    "",
    "Trigger replan flags:",
    "  --queue-low-watermark n        wake director when total queued work is at/below n while workers are active; default: 25% of candidate limit",
    "  --schedulable-low-watermark n  wake director when unlocked distinct-file work is at/below n while underfilled; default: max workers",
    "  --active-low-watermark n       long-tail active worker threshold; default: 75% of max workers",
    "  --long-tail-replan-ms n        wake director after underfilled long tail persists; default: 300000",
    "  --replan-interval-ms n         periodic director replan while workers are active; default: 0 disabled",
    "  --replan-cooldown-ms n         minimum delay between trigger-produced replan events; default: 300000",
    "  --no-blocked-queue-replan      do not wake director when queued work is blocked by active file locks",
    "",
    "Babysit flags:",
    "  --system-command <name>    child system command: bootstrap or trigger-agent; default: bootstrap",
    "  --max-restarts n           incident restarts; 0 means unlimited",
    "  --max-system-runs n        stop after n child runs; 0 means unlimited",
    "  --restart-delay-ms n       delay before a restart; default: 1000",
    "  --restart-on-clean-exit    restart even after a clean child exit",
    "  --force-recover-leases     force all active leases on non-worker incidents",
    "  --no-recover-leases        skip guardian lease recovery",
    "  --worker-thinking-level l  pass a different thinking level to worker subprocesses",
  ].join("\n");
}
